# Generated by Django 6.0.2 on 2026-03-03 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedVessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsi', models.BigIntegerField()),
                ('name', models.CharField(blank=True, max_length=200)),
                ('imo', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_vessels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'mmsi')},
            },
        ),
        migrations.CreateModel(
            name='VesselPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('sog', models.FloatField(blank=True, null=True)),
                ('cog', models.FloatField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('dest', models.CharField(blank=True, max_length=255, null=True)),
                ('eta', models.CharField(blank=True, max_length=50, null=True)),
                ('draught', models.FloatField(blank=True, null=True)),
                ('ts', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='main_app.savedvessel')),
            ],
            options={
                'indexes': [models.Index(fields=['vessel', '-ts'], name='main_app_ve_vessel__f44b79_idx')],
            },
        ),
    ]
