# Generated by Django 6.0.2 on 2026-03-03 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VesselLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('sog', models.FloatField(blank=True, null=True)),
                ('cog', models.FloatField(blank=True, null=True)),
                ('ts', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
        migrations.RemoveIndex(
            model_name='vesselposition',
            name='main_app_ve_vessel__f44b79_idx',
        ),
        migrations.AddField(
            model_name='savedvessel',
            name='raw',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='savedvessel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vessellocation',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='main_app.savedvessel'),
        ),
        migrations.DeleteModel(
            name='VesselPosition',
        ),
    ]
