# Generated by Django 6.0.2 on 2026-03-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_vessellocation_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vessellocation',
            constraint=models.UniqueConstraint(fields=('vessel', 'ts'), name='uniq_location_per_ts'),
        ),
    ]
